Create population data json.
fga-eps-mds/2020.1-stay-safe-secretary-service pull request #30
Opened 2020-10-15 17:18 UTC by brendavsantos

## Issue
Resolves #28 

## Description
Create a JSON with population data of SP and DF.

## Checklist:

- [ ] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2020-10-15 22:28 UTC, lboaventura25 approved these changes

2020-10-17 19:53 UTC, silvasara requested changes
Please change the JSON so that it looks like this:
![image](https://user-images.githubusercontent.com/30883179/96352249-2793c080-1098-11eb-944f-8fc0a026cbba.png)
In the root object,  will have the keys capture_data, census and populations, and within the object of each state you will only have the keys for state and cities

2020-10-17 22:00 UTC, silvasara approved these changes

2020-10-17 22:00 UTC, silvasara commented on src/static_data/populationData.json
> +            "state": "Federal District",
```suggestion
            "state": "Distrito Federal",
```

2020-10-17 22:01 UTC, merged