Add new filters on crime endpoint
fga-eps-mds/2020.1-stay-safe-secretary-service pull request #38
Opened 2020-10-23 22:30 UTC by herickport

## Issue
Resolves #32 

## Description

## Screenshots (if appropriate):

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

## Known problems (if appropriate):

## How to validate?

2020-10-23 23:09 UTC, lboaventura25 approved these changes

2020-10-24 14:30 UTC, rossicler requested changes

2020-10-24 14:30 UTC, rossicler commented on src/controllers/crimes_sp.py
> +def get_all_crimes_sp(params, per_capita):
This method should be generic, a controller named "crimes" that can receive a param and get crimes from 'df' or 'sp' depending on the param.

2020-10-25 02:26 UTC, renan601 approved these changes

2020-10-25 02:29 UTC, merged